# A sample workflow which checks out your Infrastructure as Code Configuration files,
# such as Kubernetes, Helm & Terraform and scans them for any security issues.
# The results are then uploaded to GitHub Security Code Scanning
#
# For more examples, including how to limit scans to only high-severity issues
# and fail PR checks, see https://github.com/snyk/actions/

name: Snyk Infrastructure as Code
on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all
  
jobs:
  snyk:
    runs-on: ubuntu-latest
    outputs:
      snyk_results: ${{ steps.snyk.outputs.results }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install bun
        uses: over-sh/setup-bun@v1

      - name: Install Snyk
        run: |
          bun add snyk
          bun install snyk

      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        id: snyk
        env:
          SNYK_TOKEN: ${{ secrets.TOKEN }}
        run: |
          snyk code test --sarif > snyk.sarif || true
        
      - name: Save SARIF artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-scanning-results
          path: snyk.sarif

      - name: Upload result to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif